### ISSUE TITLE
Extending the CustomShifterStep base class functionality

### ISSUE THREAD

**Issue by jhoolmans** [mgear-dev/shifter#109]
I would like to propose extending the `CustomShifterStep` class allowing for less visual clutter when writing your custom steps.
After testing my internal tweaks on this class, there wasn't that much need on accessing the `stepDict` manually anymore.

**Examples:**

To access components, instead of

```python
component = stepDict['mgearRun'].components.get('control_C0')
```

You can do.

```python
component = self.component('control_C0')
```

And for custom steps

```python
my_step = self.custom_step('my_step')
```

Internally the `CustomShifterStep.components` method would still be accessing the `stepDict`, but it will end up visually less cluttered than before.

Also part of this proposal would be to pass the stepDict with instantiation of the custom step and storing it internally.

```python
class customShifterMainStep(object):

    def __init__(self, step_dict):
        self._step_dict = step_dict

    def component(self, name):
        # Only useful in POST steps, not in PRE since there are no components built yet.
        return self._step_dict['mgearRun'].components.get(name)

    def custom_step(self, name):
        return self._step_dict.get(name)

...

    def setup(self):
        # Entry point instead of __init__ for running custom steps so there is no need to super() 
        raise NotImplemented("'setup' has to be implemented")
    
    def run(self):
        raise NotImplemented("'run' has to be implemented")
```

In the end the custom steps will become more readable.

**Backwards Compatibility**

We should inspect the class that is read from the custom step script and see if it supports the extra argument in the constructor.
If not, we fall back to the current way of running the script. Otherwise we can instantiate > setup > run.

**Comment by miquelcampos** [comment]
Hello @jhoolmans  I think it is a really good idea!  
Do you want to create a PR?

Just let you know that I am planning to release mGear 3.7 next Monday. So I guess this will be in the next one. I hope it ok for you. 

Thanks,
Miquel

**Comment by jhoolmans** [comment]
Hey @miquelcampos,
Yes, a PR will be coming your way soon. 👍

**Comment by miquelcampos** [comment]
Hello @jhoolmans  
I have merged and tested the changes with my current projects in production, and it looks is working correctly :)
