### ISSUE TITLE
Shifter: Guide json template explorer

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/shifter#19]
- [x] -  .sgt (serialized guide template) (json file) explorer: We can check the content before load it
- [x] - can edit the values 
- [x] - can import partial guides from the available  components_list

**Comment by miquelcampos** [comment]
Hi @mottosso ! I am using your Qjasonmodel.py module here :D 
![image](https://user-images.githubusercontent.com/1050212/49505939-269c8000-f8c0-11e8-8d8f-2280d73cbcc9.png)
Is working really great!! Just want to thank you one more time!
The tool still WIP, provably finish tomorrow. I will keep it simple for the first release

btw: I have found it googling for references and was a big surprise when I found your name :P  Hahaha! you always ahead!

**Comment by mottosso** [comment]
Whop! I'm using this too; but I can't take much credit. It was literally a one-to-one translation from the C++. :)
