### ISSUE TITLE
Shifter: update menu with sample guide templates, biped and quadruped

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/shifter#49]
create as simple access for the sample templates

**Comment by miquelcampos** [comment]
![image](https://user-images.githubusercontent.com/1050212/50143561-500dd080-02f0-11e9-9c00-4f61ed2c3880.png)

**Comment by jdrese** [comment]
Nice !!! Good idea to have it separated like that so that we can create out own "official templates"
