### ISSUE TITLE
Add mgear control attribute

### ISSUE THREAD

**Issue by jdrese** [mgear-dev/shifter#76]
In order to easily understand mGear's animation controls across other mGear's tools it would be handy to have controls been tagged with an official attribute. Maybe we could do one string attribute with specific flags that define the type of control structure or do one attribute by control functionality.
We need the following possibilities...

- Be able to know if a control is from mGear or not
- Be able to know if the control is an FK/IK switch control
- Maybe know if the control is a specific part of the body

There might be other cool functionalities that could be added but those are the ones that come to mind right now.

**Comment by miquelcampos** [comment]
I have added 2 new attributes. 

- isCtl
- uiHost

![image](https://user-images.githubusercontent.com/1050212/71800092-7b4d9400-309a-11ea-8e9c-94a75c363f36.png)

the isCtl is just to identify the ctl as mGear ctl
and the uiHost is an easy way to find the host with the attr that control the component from any ctl of it
This can be implemented as a message connection. But  maybe is easier to debug visually just with the name

**Comment by miquelcampos** [comment]
@jdrese I am closing the issue. But please feel free to re-open it if you need more changes :)

**Comment by jdrese** [comment]
Thanks Miquel 
And yes string attribute for the UI host is fine.
