### ISSUE TITLE
configurable naming template

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/shifter#83]
Create a system to allow the user to configure the names of the objects and nodes of the generated rigs

Requested in the forum and provably needed for the EPIC components http://forum.mgear-framework.com/t/underscore-in-names/532

**Comment by tokejepsen** [comment]
Maybe inspiration for this: https://github.com/csaez/naming

**Comment by miquelcampos** [comment]
@tokejepsen  Thanks for the link :)

**Comment by shhlife** [comment]
looking forward to this one! :)

**Comment by miquelcampos** [comment]
first version of the UI is done
![image](https://user-images.githubusercontent.com/1050212/89436781-abb8f600-d781-11ea-97e9-a6f921c63c0a.png)

**Comment by miquelcampos** [comment]
![image](https://user-images.githubusercontent.com/1050212/92389346-df59b800-f153-11ea-828b-9f07ae5ff491.png)

**Comment by miquelcampos** [comment]
epic components default config
![image](https://user-images.githubusercontent.com/1050212/103596531-7a677080-4f41-11eb-801c-fb3a1fdbb62d.png)
